### PR TITLE
API3 exceptions: catch and log as errors, return FALSE, check return …

### PR DESCRIPTION
**Pull request by sebalis**
…values of _contributionrecur_pp_info for falsity

My solution for issue #20.

### CODE REVIEW

**Comment by romymy** [comment]
@adixon It would be great if this pull request could be merged. Without the code adjustment of the PR, there is unfortunately a conflict with the extension [org.project60.sepa](https://github.com/Project60/org.project60.sepa), which is very commonly used in German-speaking countries. We have been patching all of our customer projects with it for a year and have not found any problems so far.

**Comment by sebalis** [comment]
@adixon Between my original submission and @romymy’s comment, other changes to `contributionrecur.php` had introduced merge conflicts. I have now merged the master branch into mine and manually resolved these conflicts. The display of changes here on Github is a bit confusing in the sections from lines 183 and 220. All I did there is to add a check of `$class_name` (the result of `_contributionrecur_pp_info`) and indent the following lines accordingly. If no class name was found, the code that relies on it has to be skipped.

I also pushed two commits to implement the corresponding to-do on error logging somewhat less lazily than I had done before. I’m now logging specific messages in the two cases where a) an exception was encountered or b) an empty result is found. I had to force-push once because I originally mistyped a commit message.

I would now very much second the request that this PR be merged and released. Romy has already described the impact, it is very much felt by us at civiservice.de (a CiviCRM partner and contributor from Germany).

**Comment by adixon** [comment]
Thanks to both of you, and apologies for not paying attention last October. The PR looks fine, thank you for the explanation.

As an aside, I wasn't aware that this extension was in such use! I'm assuming it's the offline recurring that you're using - I think it's more common for offline payments to get tracked outside of the US than in. Glad to know it's useful.

As a second aside - this extension has grown into quite a mess of features. I've been extracting the "Recurring UX" bit out into it's own extension, here: https://lab.civicrm.org/extensions/recurux so I'll be eventually ripping that part out of this extension.

**Comment by romymy** [comment]
Thanks for the quick response, @adixon, I appreciate it. 

We need the option to force recurring-only donations in a native CiviCRM online donation page, e.g. if the form is to become a member whose membership automatically renews at a fixed interval. In Germany or even Europe, the focus is more on members and their regular membership fee and less on one-time donations than is the case in the USA, from what I heard.

The standard form does offer the option "Select recurring donations by default?", but the user can deselect that at any time - so it's not enough for the membership forms. 

One thought: I wonder if your extensions should be associated to the Plugins [RadioButton](https://civicrm.org/extensions/radiobuttons) and [RecurringButtons](https://lab.civicrm.org/extensions/recurringbuttons) and the new RiverLea theme (e.g. by working with the same variables in the CSS or something like this). But maybe the effort isn't worth it if the native forms are superseded by FormBuilder sooner or later ...

**Comment by adixon** [comment]
Forcing recurring-only is sure a handy feature, and super easy, code-wise, though this extension's current implementation is not very lovely as far as the admin interface and the configuration settings. Switching a site to use the new extension after I deprecate that function in here should be easy enough!

**Pull request merged**
