### PR TITLE
Allow default but not forced recurring

### PR DESCRIPTION
**Pull request by MegaphoneJon**
I had a client who wanted the "recurring" checkbox to default to true, but not forced to true, as do a couple folks on Stack Exchange.  Since your extension is so close in functionality, I thought it made more sense to add it as an option rather than a whole new extension or custom tweak.

### CODE REVIEW

**Comment by adixon** [comment]
Thanks for this, nice to see that you included it on the individual page options as well.

What's your thinking about the incompatibility of the force and default options? Is there a way to make sense of having both of those checkboxes selected?

Alternatively, perhaps instead the force checkbox should actually be a select option for force, default or nothing?

**Comment by MegaphoneJon** [comment]
I considered that, and figured that someone who selected both "force" and "default" would get the expected behavior.  If you'd prefer "default" to be an option on "force" I'm happy to do that too.  Let me know.

**Comment by adixon** [comment]
Okay, no - I think I understand now. I think your code is fine as is, it just needs more clarification in the documentation to say that the recur_default option has no effect if the force recurring is on.

**Comment by MegaphoneJon** [comment]
Seeing your update to this extension prompted me to incorporate your feedback above!

**Pull request merged**
